name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
category-template: '## $TITLE'

sort-by: 'title'
sort-direction: 'ascending'

prerelease: false

categories:
  - type: "pre-exclude"
    when:
      labels:
        - 'skip-changelog'
        - 'github_actions'
        - 'code-style'
        - 'dependabot'
        - 'statuses'
        - 'build'
  - title: 'Added'
    when:
      label: 'added'
  - title: 'Changed'
  - title: 'Removed'
    when:
      label: 'removed'
  - title: 'Fixed'
    when:
      labels:
        - 'fix'
        - 'bug'
  - title: 'Machine translations'
    collapse-after: 20
    when:
      label: 'machine'
  - title: 'Dependencies'
    collapse-after: 10
    when:
      label: 'dependencies'
  - title: 'Security'
    when:
      labels:
        - 'security'
        - 'security fix'
        - 'security vulnerability'
  - type: "version-resolver"
    semver-increment: "major"
    when:
      labels:
        - 'major'
        - 'removed'
  - type: "version-resolver"
    semver-increment: "minor"
    when:
      labels:
        - 'minor'
        - 'added'
        - 'feature'
  - type: "version-resolver"
    semver-increment: "patch"

template: $CHANGES
