name: "Deploy"

on:
  workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    tools: deployer:^v7.0.0-rc.6

            -   name: Deploy
                uses: deployphp/action@v1
                with:
                    private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
                    dep: deploy production --revision=${{ github.sha }}
