name: "Deploy"

on:
  workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv

            -   name: Set Up
                run:  |
                    mkdir -p ~/.ssh
                    chmod 700 ~/.ssh
                    echo ${{ secrets.DEPLOY_PRIVATE_KEY }} >> ~/.ssh/id_rsa
                    chmod 600 ~/.ssh/id_rsa
                    echo "StrictHostKeyChecking no" >> ~/.ssh/known_hosts
                    chmod 600 ~/.ssh/known_hosts

            -   name: Install dependencies
                run: composer global require deployer/deployer:^v7.0.0-rc.6

            -   name: Deploy
                run: dep deploy production --revision=${{ github.sha }}
