name: Release Drafter

on:
  workflow_call:
    outputs:
      tag_name:
        description: "Tag name"
        value: ${{ jobs.update_release_draft.outputs.tag_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    name: Release Draft
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.release_drafter.outputs.tag_name }}

    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
